version: '3.1'

services:

  db:
    container_name: PassMaster-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ChatMasterDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    container_name: PassMaster-adminer
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - "9080:8080"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "9081:80"
      - "9025:25"

  api:
    build:
      context: ./PassMaster-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./PassMaster-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
volumes:
  mysql-data:
  frontend-data:
