version: '3.1'

services:

  db:
    container_name: PassMaster-db
    image: mysql:8.1.0-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3308:3306"

  adminer:
    container_name: PassMaster-adminer
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - "9080:8080"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "9081:80"
      - "9025:25"